services:
  contact-service:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./services/contact-service:/app
    command: sh -c "npm install && npm run start"
    environment:
      - PORT=4001
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "4001:4001"
